clear;
load('data/lineal/modelos/rango_bajo');
modelo_lineal_rango_bajo = modelo_armax_op;
X0_bajo = X0_armax;
load('data/lineal/modelos/rango_medio');
modelo_lineal_rango_medio = modelo_armax_op;
X0_medio = X0_armax;
load('data/lineal/modelos/rango_alto');
modelo_lineal_rango_alto = modelo_armax_op;
X0_alto = X0_armax;
load('model_parameters.mat');